aertslab/CREsted

src/crested/pl/heatmap/_correlations.py

- **Improve correlations_self computation time**
```python
rng = np.random.default_rng(seed = 123)
x = rng.random((100, 200))
def old(X):
c = np.zeros((X.shape[0], X.shape[0]))
for i in range(X.shape[0]):
for j in range(X.shape[0]):
c[i, j] = np.corrcoef(X[i, :], X[j, :])[0, 1]
return c
def new(X):
c = np.corrcoef(X)
return c
%time a = old(x)
CPU times: user 388 ms, sys: 925 μs, total: 389 ms
Wall time: 389 ms
%time b = new(x)
CPU times: user 351 μs, sys: 0 ns, total: 351 μs
Wall time: 321 μs
np.allclose(a, b)
True
```
- **Improve correlation_predictions speed**
```python
rng = np.random.default_rng(seed = 123)
x = rng.random((100, 200))
y = rng.random((100, 200))
def old(X, Y):
c = np.zeros((X.shape[0], X.shape[0]))
for i in range(X.shape[0]):
for j in range(X.shape[0]):
c[i, j] = …
```

improve correlation correlation speed

---

pyproject.toml
src/crested/tl/_tfmodisco.py

Scanpy is not needed as dependency. It was only used to read anndata and get count matrix, which can also be done with `anndata`, which was already a dependency.
Best,
Seppe

Remove scanpy dependency (not needed).

---

src/crested/pl/patterns/_modisco_results.py
src/crested/tl/_modisco_utils.py
src/crested/tl/_tfmodisco.py

Necessary bug fixes in pattern matching analysis + notebook updates.
Nothing crazy

Necessary bug fixes in pattern matching code

---

src/crested/tl/_tfmodisco.py

In some cases (when there is a match between cell types of the first pattern) a pattern might not have an IC value. Now they do!

make sure pattern always has ic!

---

src/crested/tl/_crested.py

warn users when running crested.test() that this will not work if the model is not compiled

add warning if model not compiled

---

docs/api/utils.md
docs/tutorials/model_training_and_eval.ipynb
pyproject.toml
src/crested/_io.py
src/crested/pl/hist/_locus_scoring.py
src/crested/utils/__init__.py
src/crested/utils/_utils.py

Updates the bigwig track reading (for visualisation, i.e. for genome scanning comparisons, and for models later on).
Three changes + one bonus:
I added a function in `_io`, `_extract_tracks_from_bigwig()` which wraps around pybigtools' `values()`.
It supports binning by default, and is intended to be a robust backend function for reading in bigwig tracks. It could be faster by requesting some changes in pybigtools, see below. 
The old function (`extract_bigwig_values_per_bp`) is still there, with the backend changed to the new function. 
However, the way it works is very counterintuitive, as it asks for a list of regions but then returns the values for everything between the min and max of those regions, and completely ignores different potential chromosomes of the different regions. …

Remove pybigwig from bw track reading

---

docs/api/utils.md
docs/conf.py
docs/references.bib
docs/references.md
src/crested/tl/_crested.py
src/crested/utils/__init__.py
src/crested/utils/_utils.py

- add utility function for sequence fetching (=pysam wrapper)
- add references
- add dvc logging option in fit()

Seq utilities and loggign

---

src/crested/tl/_crested.py
src/crested/tl/data/_anndatamodule.py
src/crested/tl/data/_dataset.py

Adds support for stranded datasets (so anndatas with indices (chr:start-end:strand), like gene data) while preserving support for non-stranded datasets (like ATAC data). I checked whether loading data works with stranded and unstranded data in-memory and not in-memory and with/without always_reverse_complement.
To do still:
Also has two small bugfixes:
- `get_embeddings()` was trying to save per-gene embeddings in `anndata.obsm` (which is for per-pseudobulk observations). Changed this to `.varm` and tested that it works.
- the `Crested.enhancer_design_*` functions were deriving start and end from the var columns, but that's not robust: the the anndataset object always reads the full region string to get start and end, and indeed in my code (and I believe also if you use the expand region …

Add strand support to AnnDataset and fix deterministic_shift

---

.github/workflows/docs_upload.yaml
src/crested/tl/_crested.py

Don't always upload docs when pushing to main, but only on a new release.
Tried adding a 'version picker' box, but this is not supported with our default theme.

only upload docs on release

---

README.md
pyproject.toml
src/crested/tl/modisco/_modisco_utils.py

tangermeme installs torch and causes issues with a tensorflow backend environment.
Now crested raises a warning to pip install tangermeme only when trying to use the function it requires.

move tangermeme dep out of optional dependencies

---

docs/tutorials/model_training_and_eval.ipynb
src/crested/tl/_crested.py
tests/test_pipeline.py

- Will continue training from last found checkpoint if the same project and run_name are initialized in the Crested(..) class
This changes the previous behaviour of overwriting that folder if it already existed.
- Fixes an issue that would always recompile when doing a fit() so optimizer states weren't continued.

continue training from existing checkpoint

---

src/crested/tl/_explainer_torch.py
tests/test_pipeline.py

Explicitly sets array dtypes in torch contribution scores calculations to avoid errors if user has mismatched numpy versions.

Bugfix pt contribution numpy2

---

src/crested/tl/_crested.py
tests/test_pipeline.py

- removed incorrect return None that caused only one test metric to be logged and the return_metrics to not work
- added unit test that checks for this

fix incorrect return None in Crested.test(...)

---

docs/tutorials/model_training_and_eval.ipynb
src/crested/tl/losses/_cosinemse_log.py

add multiplier parameter instead of standard multiplication of predicted values by 1000

update msecosine log loss function

---

src/crested/pp/_regions.py

Mini fix, I missed something when originally fixing this. 
change_regions_width would no longer complain about lack of chromsizes if Genome was registered, but didn't actually do the chromsizes check.
If we don't do a release soon, this might be worth a small bugfix subrelease?

Fix change_regions_width not using Genome chromsizes

---

pyproject.toml
src/crested/_io.py

adata.X matrix shape was not matching up with length of .var_names if regions were outside chromosome sizes during import_bigwigs.
Fixed here by always creating the temp bed file (where the check for chromsizes happens).

correctly adjust bed file if outside of chromsizes

---

src/crested/tl/_explainer.py
src/crested/tl/_explainer_tf.py
src/crested/tl/_explainer_torch.py
src/crested/tl/_tools.py

I was still running out of GPU memory for expected integrated gradients and Borzoi, even when getting gradients for one sequence. Figured out that it was loading the 650 sequences into GPU memory, and that didn't fit next to the calculations, even if we immediately took the gradients off the GPU. Thought I'd tested all combinations, turns out I didn't.
This rework has tested all three explainers (saliency_map, integrated_grad and expected_integrated_grad) for DilatedCNN (3 seqs & 500 seqs) & Borzoi (3 seqs), for both TensorFlow and PyTorch. 
It moved to appending gradient batches to list and concatenating (since that's what keras' model.predict() also does, and it's just as fast as writing to pre-made array). It also only explicitly moves one batch of sequences to tensor/GPU at a time …

More explainer changes

---

src/crested/pl/locus/_locus_scoring.py

Added validation logic for the `highlight_positions` parameter in the `locus_scoring` function. The function now raises a ValueError when any highlight position falls outside the specified genomic range.

Raise error in locus plotting when highlighted positions are out of range

---

src/crested/utils/_utils.py

Before using the var names was a lot slower for more exotic chromosomes.
Just getting chrom, start, and end is a lot faster

faster sequence loader from anndata in _transform_input

---

src/crested/_genome.py
src/crested/pl/patterns/_utils.py
src/crested/tl/_tools.py
src/crested/tl/modisco/_tfmodisco.py
src/crested/utils/_utils.py

when you do crested.tl.predict() on a large dataset, it throws OOM errors because it first copies the whole thing to GPU. Workaround is to do manual batching which can be set quite big. None default so just for edge cases.

avoiding GPU OOM errors with crested.tl.predict on large datasets
